# Implementation of the Discrete Empirical Interpolation Method (DEIM)

In [3]:
import numpy as np

In [134]:
def cur(A):
    
    def select(V,rank,axis):
        if axis:
            V = np.transpose(V)
        p = np.zeros(rank, dtype=int) # to store indices of rows of V
        p[0] = np.argmax(np.abs(V[:,0])) # row index of the largest value in the first column of V
        for i in range(1,rank):
            v1 = V[:,i]
            v0 = V[:,i-1]
            res = v1 - (v1[p[i-1]]/v0[p[i-1]]) * v0
            p[i] = np.argmax(np.abs(res))
        R = V[p]
        return np.transpose(R) if axis else R
             
    V = np.linalg.svd(A)[0]
    rank = np.linalg.matrix_rank(A)
    R = select(V,rank,0)
    C = select(V,rank,1)
    U = 0 #np.linalg.pinv(C) @ A @ np.linalg.pinv(R)
    return C,U,R

In [135]:
A = np.array([[1,0,0],[0,1,0],[0,0,1],[1,1,0]])
C,U,R = cur(A)

In [136]:
print(C)

[[ 7.07106781e-01 -5.77350269e-01  0.00000000e+00]
 [-7.07106781e-01 -5.77350269e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-1.66533454e-16  5.77350269e-01  0.00000000e+00]]


In [137]:
print(U)

0


In [138]:
print(R)

[[-8.16496581e-01  0.00000000e+00 -1.66533454e-16  5.77350269e-01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.08248290e-01  0.00000000e+00 -7.07106781e-01 -5.77350269e-01]]
