# Implementation of the Discrete Empirical Interpolation Method (DEIM)

In [1]:
import numpy as np

In [2]:
def cur(A):
    rank = np.linalg.matrix_rank(A)
    p = np.zeros(rank, dtype=int) # array of indices
    
    def select(Vt, axis): # Easier access to columns of V if we use V^T
        p[0] = np.argmax(np.abs(Vt[0])) # row index of the largest value in the first column of V
        for i in range(1,rank):
            v1 = Vt[i]
            v0 = Vt[i-1]
            res = v1 - (v1[p[i-1]]/v0[p[i-1]]) * v0
            p[i] = np.argmax(np.abs(res))
        return np.transpose(np.transpose(A)[p]) if axis else A[p]
    
    C = select(np.transpose(np.linalg.svd(np.transpose(A))[0]), 1)
    R = select(np.transpose(np.linalg.svd(A)[0]), 0)
    U = np.linalg.pinv(C) @ A @ np.linalg.pinv(R)
    return C,U,R

# Example 1, m > n = r

In [3]:
A = np.array([[1,0,0],[0,3,0],[0,0,2],[1,1,0]])
C,U,R = cur(A)
print("A =\n", A)
print("C =\n", C)
print("U =\n", U)
print("R =\n", R)

A =
 [[1 0 0]
 [0 3 0]
 [0 0 2]
 [1 1 0]]
C =
 [[0 0 1]
 [3 0 0]
 [0 2 0]
 [1 0 1]]
U =
 [[ 3.33333333e-01  0.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  5.00000000e-01  0.00000000e+00]
 [-7.40148683e-17  0.00000000e+00  1.00000000e+00]]
R =
 [[0 3 0]
 [0 0 2]
 [1 0 0]]


# Example 2, m < n = r

In [4]:
A = np.array([[1,0,0,0],[0,3,0,0],[0,0,2,0]])
C,U,R = cur(A)
print("A =\n", A)
print("C =\n", C)
print("U =\n", U)
print("R =\n", R)

A =
 [[1 0 0 0]
 [0 3 0 0]
 [0 0 2 0]]
C =
 [[0 0 1]
 [3 0 0]
 [0 2 0]]
U =
 [[0.33333333 0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         1.        ]]
R =
 [[0 3 0 0]
 [0 0 2 0]
 [1 0 0 0]]


# Example 3, m = n = r

In [5]:
A = np.array([[1,0,0],[0,3,0],[0,0,2]])
C,U,R = cur(A)
print("A =\n", A)
print("C =\n", C)
print("U =\n", U)
print("R =\n", R)

A =
 [[1 0 0]
 [0 3 0]
 [0 0 2]]
C =
 [[0 0 1]
 [3 0 0]
 [0 2 0]]
U =
 [[0.33333333 0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         1.        ]]
R =
 [[0 3 0]
 [0 0 2]
 [1 0 0]]


# Example 4, m = n < r

In [6]:
A = np.array([[1,0,0],[0,3,0],[0,2,0]])
C,U,R = cur(A)
print("A =\n", A)
print("C =\n", C)
print("U =\n", U)
print("R =\n", R)

A =
 [[1 0 0]
 [0 3 0]
 [0 2 0]]
C =
 [[0 1]
 [3 0]
 [2 0]]
U =
 [[ 3.33333333e-01  0.00000000e+00]
 [-2.96059473e-16  1.00000000e+00]]
R =
 [[0 3 0]
 [1 0 0]]


# This A was used in the other script. Comparing results.

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
C,U,R = cur(A)
print("A =\n", A)
print("C =\n", C)
print("U =\n", U)
print("R =\n", R)

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
C =
 [[ 3  1]
 [ 6  4]
 [ 9  7]
 [12 10]]
U =
 [[-0.05555556  0.55555556]
 [ 0.16666667 -0.66666667]]
R =
 [[10 11 12]
 [ 1  2  3]]
